language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install: "sudo apt-get install libhdf4-dev"
# command to run tests
script: ./runexamples.sh
notifications:
  email:
    recipients:
      - eoshelp@hdfgroup.org
    on_success: never
    on_failure: change
